/** Auto-generated by tools/gen_priority_qll.py; do not edit. */
// DBMS: monetdb; source: /root/SQLeek/sqleek_pipeline/stage0_pre_processing/output/monetdb_priority_scores.json
import cpp

predicate isPriorityFunction(Function f) {
  f.getName() = "monetdbe_query_internal"
  or
  f.getName() = "monetdbe_bind"
  or
  f.getName() = "bs_write"
  or
  f.getName() = "write_out"
  or
  f.getName() = "BATguess_uniques"
  or
  f.getName() = "BATjoin"
  or
  f.getName() = "resetMalBlk"
  or
  f.getName() = "freeMalBlk"
  or
  f.getName() = "rel_unnest_dependent"
  or
  f.getName() = "push_up_join"
  or
  f.getName() = "rel_has_freevar"
  or
  f.getName() = "rel_rename"
  or
  f.getName() = "rel_set_type"
  or
  f.getName() = "exp_set_type"
  or
  f.getName() = "move_join_exps"
  or
  f.getName() = "push_up_project_exp"
  or
  f.getName() = "push_up_select"
  or
  f.getName() = "push_up_project"
  or
  f.getName() = "rel_dependent_var"
  or
  f.getName() = "run_exp_rewriter"
  or
  f.getName() = "rel_general_unnest"
  or
  f.getName() = "bind_join_vars"
  or
  f.getName() = "rel_unnest"
  or
  f.getName() = "_rel_unnest"
  or
  f.getName() = "exp_freevar"
  or
  f.getName() = "rewrite_empty_project"
  or
  f.getName() = "rel_freevar"
  or
  f.getName() = "rel_bound_exp"
  or
  f.getName() = "rel_cast"
  or
  f.getName() = "rel_order_by"
  or
  f.getName() = "rel_select_exp"
  or
  f.getName() = "push_up_select_l"
  or
  f.getName() = "exp_reset_card_and_freevar_set_physical_type"
  or
  f.getName() = "rewrite_split_select_exps"
  or
  f.getName() = "aggrs_complex"
  or
  f.getName() = "aggrs_split_funcs"
  or
  f.getName() = "add_missing_project_exps"
  or
  f.getName() = "push_up_project_exps"
  or
  f.getName() = "rel_reduce2one_exp"
  or
  f.getName() = "exp_has_freevar"
  or
  f.getName() = "exp_inline_arg"
  or
  f.getName() = "rel_unnest_projects"
  or
  f.getName() = "aggrs_split_args"
  or
  f.getName() = "rel_bind_vars"
  or
  f.getName() = "rel_union_exps"
  or
  f.getName() = "exp_physical_types"
  or
  f.getName() = "rel_simplify_exp_and_rank"
  or
  f.getName() = "exp_in_project"
  or
  f.getName() = "exp_is_count"
  or
  f.getName() = "rewrite_aggregates"
  or
  f.getName() = "exp_in_compare"
  or
  f.getName() = "add_missing_project_exp"
  or
  f.getName() = "rewrite_remove_xp_project"
  or
  f.getName() = "push_up_select2"
  or
  f.getName() = "rewrite_exp_rel"
  or
  f.getName() = "run_rel_rewriter"
  or
  f.getName() = "exp_only_freevar"
  or
  f.getName() = "rel_only_freevar"
  or
  f.getName() = "rel_unnest_simplify"
  or
  f.getName() = "exp_reset_props"
  or
  f.getName() = "exp_rewrite"
  or
  f.getName() = "rel_bind_var"
  or
  f.getName() = "exp_set_freevar"
  or
  f.getName() = "rel_inline_table_func"
  or
  f.getName() = "rel_unnest_comparison_rewriters"
  or
  f.getName() = "add_null_projects"
  or
  f.getName() = "rewrite_join2semi"
  or
  f.getName() = "_rel_aggr"
  or
  f.getName() = "exp_bin"
  or
  f.getName() = "rel2bin_project"
  or
  f.getName() = "rel_column_ref"
  or
  f.getName() = "rel_with_query"
  or
  f.getName() = "exp_atom_set_type_null"
  or
  f.getName() = "push_up_projects"
  or
  f.getName() = "exp_replace_exp_using_label"
  or
  f.getName() = "exp_set_type_as"
  or
  f.getName() = "list_exps_replace_exp_using_label"
  or
  f.getName() = "exp_bin_conjunctive"
  or
  f.getName() = "rel_groupings"
  or
  f.getName() = "rel_value_exp2"
  or
  f.getName() = "rel2bin_antijoin"
  or
  f.getName() = "rel_logical_value_exp"
  or
  f.getName() = "rel_in_value_exp"
  or
  f.getName() = "rel_get_count"
  or
  f.getName() = "rel_rankop"
  or
  f.getName() = "rel_group_column"
  or
  f.getName() = "exp_key"
  or
  f.getName() = "rel_lastexp"
  or
  f.getName() = "rel_having_limits_nodes"
  or
  f.getName() = "rel_select_push_filter_exp_down"
  or
  f.getName() = "simple_selection"
  or
  f.getName() = "rel_subquery_optname"
  or
  f.getName() = "exp_valid"
  or
  f.getName() = "rel_column_exp"
  or
  f.getName() = "group_by_pk_project_uk_cond"
  or
  f.getName() = "rel_table_exp"
  or
  f.getName() = "rel_selects"
  or
  f.getName() = "rel_orderby"
  or
  f.getName() = "bind_func_"
  or
  f.getName() = "rel_compare_exp"
  or
  f.getName() = "rel_exists_exp"
  or
  f.getName() = "push_join_exp"
  or
  f.getName() = "rel_query"
  or
  f.getName() = "_rel_nop"
  or
  f.getName() = "rel_nop"
  or
  f.getName() = "rel_case"
  or
  f.getName() = "exp_fix_scale"
  or
  f.getName() = "exp_exist"
  or
  f.getName() = "sql_insert_triggers"
  or
  f.getName() = "rel_compare"
  or
  f.getName() = "rel_unique_names"
  or
  f.getName() = "rel_setquery_corresponding"
  or
  f.getName() = "query_exp_optname"
  or
  f.getName() = "rel_filter_exp_"
  or
  f.getName() = "rel_table_optname"
  or
  f.getName() = "rel_exists_value_exp"
  or
  f.getName() = "exp_is_not_intern"
  or
  f.getName() = "sql_reorder"
  or
  f.getName() = "rel_loader_function"
  or
  f.getName() = "exp_between_check_types"
  or
  f.getName() = "rel_reduce_on_column_privileges"
  or
  f.getName() = "rel_where_groupby_nodes"
  or
  f.getName() = "schema_selects"
  or
  f.getName() = "exp_tuples_set_supertype"
  or
  f.getName() = "rel_file_loader"
  or
  f.getName() = "rel_in_exp"
  or
  f.getName() = "join_on_column_name"
  or
  f.getName() = "rel_joinquery_"
  or
  f.getName() = "rel_nop_"
  or
  f.getName() = "rel_unop_"
  or
  f.getName() = "rel_order_by_column_exp"
  or
  f.getName() = "sql_insert_check"
  or
  f.getName() = "rel_binop_check_types"
  or
  f.getName() = "rel_subquery"
  or
  f.getName() = "bind_func"
  or
  f.getName() = "rel_named_table_function"
  or
  f.getName() = "rel_next_value_for"
  or
  f.getName() = "rel_value_exp"
  or
  f.getName() = "subrel_project"
  or
  f.getName() = "rel_setquery_n_ary_"
  or
  f.getName() = "is_project_true"
  or
  f.getName() = "rel_partition_groupings"
  or
  f.getName() = "rel_table_projections"
  or
  f.getName() = "rel_exp_variable_on_scope"
  or
  f.getName() = "rel_joinquery"
  or
  f.getName() = "rel_select_push_compare_exp_down"
  or
  f.getName() = "rel_binop_"
  or
  f.getName() = "rel2bin_groupjoin"
  or
  f.getName() = "rel_complex_case"
  or
  f.getName() = "exp_has_rank"
}
